/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AnimusicIndexImport } from './routes/animusic/index'
import { Route as AnimusicCallbackImport } from './routes/animusic/callback'

// Create/Update Routes

const AnimusicIndexRoute = AnimusicIndexImport.update({
  id: '/animusic/',
  path: '/animusic/',
  getParentRoute: () => rootRoute,
} as any)

const AnimusicCallbackRoute = AnimusicCallbackImport.update({
  id: '/animusic/callback',
  path: '/animusic/callback',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/animusic/callback': {
      id: '/animusic/callback'
      path: '/animusic/callback'
      fullPath: '/animusic/callback'
      preLoaderRoute: typeof AnimusicCallbackImport
      parentRoute: typeof rootRoute
    }
    '/animusic/': {
      id: '/animusic/'
      path: '/animusic'
      fullPath: '/animusic'
      preLoaderRoute: typeof AnimusicIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/animusic/callback': typeof AnimusicCallbackRoute
  '/animusic': typeof AnimusicIndexRoute
}

export interface FileRoutesByTo {
  '/animusic/callback': typeof AnimusicCallbackRoute
  '/animusic': typeof AnimusicIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/animusic/callback': typeof AnimusicCallbackRoute
  '/animusic/': typeof AnimusicIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/animusic/callback' | '/animusic'
  fileRoutesByTo: FileRoutesByTo
  to: '/animusic/callback' | '/animusic'
  id: '__root__' | '/animusic/callback' | '/animusic/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AnimusicCallbackRoute: typeof AnimusicCallbackRoute
  AnimusicIndexRoute: typeof AnimusicIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AnimusicCallbackRoute: AnimusicCallbackRoute,
  AnimusicIndexRoute: AnimusicIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/animusic/callback",
        "/animusic/"
      ]
    },
    "/animusic/callback": {
      "filePath": "animusic/callback.tsx"
    },
    "/animusic/": {
      "filePath": "animusic/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
